# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
        - id: trailing-whitespace  # убирает лишние пробелы
        - id: check-added-large-files  # проверяет тяжелые файлы на изменения
        - id: end-of-file-fixer  # добавляет пустую строку в конце файла
        - id: check-yaml  # проверяет синтаксис .yaml файлов
        - id: check-json  # проверяет синтаксис .json файлов
        - id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
        - id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
        - id: mypy
          exclude: ^tests/
          additional_dependencies: [pydantic]
