version: '3.8'

volumes:
  pg_data:

networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    networks:
      dev:
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    expose:
      - "5432"

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    networks:
      dev:
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
