version: '3.8'

volumes:
  pg_data:

networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    networks:
      dev:
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    expose:
      - "5432"

    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  redis_cache:
    image: redis:7.2-rc2
    container_name: redis
    networks:
      dev:
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: on-failure
    env_file:
      - .env
    expose:
      - "6379"

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    networks:
      dev:
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
